# Site settings
title: Mission Viejo Cowboys Football and Cheer
email: mvcowboysinfo@gmail.com
description: "Mission Viejo Cowboys Football and Cheer program"
baseurl: ""
url: "http://localhost:4000"
twitter_username: mvcowboys
github_username:  jrepp

# Build settings
markdown: redcarpet
permalink: pretty
safe: true
lsi: false
hilighter: true
paginate: 10
exclude: ["scripts", "Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss']
